matrix:
  include:
    # - os: linux
    #   sudo: required
    #   env: BUILDARCH=x64
    #   dist: trusty
    # - os: linux
    #   sudo: required
    #   env: BUILDARCH=arm64
    #   dist: trusty
    # - os: linux
    #   sudo: required
    #   env: BUILDARCH=arm
    #   dist: trusty
    - os: osx

language: node_js
node_js: "12"

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export GITHUB_TOKEN="foo"
  - . install_deps.sh
  - . get_repo.sh
  - . check_tags.sh

script:
  - ./build.sh

before_deploy:
  - ./sign_mac_app.sh
  - ./create_zip.sh
  - ./create_dmg.sh
  - ./sum.sh

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  name: $LATEST_MS_TAG
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ./*.sha256
    - ./*.zip
    - ./*.tar.gz
    - ./*.dmg
    - ./*.deb
    - ./*.rpm
    - ./*.AppImage
    - ./*.AppImage.zsync
  on:
    all_branches: true
    condition: $SHOULD_BUILD = yes

# after_deploy:
#   - ./update_version.sh
